consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  GoaLocalCouncillor:
    description: A Councillor (default view)
    example:
      address: Velit quia commodi dolorem.
      area: In harum dolores consequatur et.
      county: Ipsum optio magnam eos.
      email: Et non similique.
      facebook: Eos earum vitae magnam sunt.
      firstName: Quod sunt quibusdam suscipit eos sequi dolores.
      id: Dolor mollitia.
      image: Recusandae aut.
      party: Recusandae qui mollitia blanditiis corrupti.
      phone: Omnis aspernatur dignissimos eligendi.
      secondName: Eligendi aut corporis.
      twitter: Iste cumque cum ea quod.
      web: Aliquam qui.
    properties:
      address:
        default: ""
        description: a phone contact for the user
        example: Velit quia commodi dolorem.
        type: string
      area:
        default: ""
        description: The area of the users local council
        example: In harum dolores consequatur et.
        type: string
      county:
        default: ""
        description: The area of the users local council
        example: Ipsum optio magnam eos.
        type: string
      email:
        default: ""
        description: email for the councillor
        example: Et non similique.
        type: string
      facebook:
        description: facebook handle for the user
        example: Eos earum vitae magnam sunt.
        type: string
      firstName:
        description: Name of the user
        example: Quod sunt quibusdam suscipit eos sequi dolores.
        type: string
      id:
        description: db id
        example: Dolor mollitia.
        type: string
      image:
        default: ""
        description: an image url for the user
        example: Recusandae aut.
        type: string
      party:
        default: ""
        description: the councillors party
        example: Recusandae qui mollitia blanditiis corrupti.
        type: string
      phone:
        default: ""
        description: a phone contact for the user
        example: Omnis aspernatur dignissimos eligendi.
        type: string
      secondName:
        description: Name of the user
        example: Eligendi aut corporis.
        type: string
      twitter:
        description: twitter handle for the user
        example: Iste cumque cum ea quod.
        type: string
      web:
        default: ""
        description: a web link for the user
        example: Aliquam qui.
        type: string
    required:
    - firstName
    - secondName
    - area
    - image
    - phone
    - email
    - party
    - address
    - county
    title: 'Mediatype identifier: application/vnd.goa.local.councillor+json; view=default'
    type: object
  GoaLocalCouncillorCollection:
    description: GoaLocalCouncillorCollection is the media type for an array of GoaLocalCouncillor
      (default view)
    example:
    - address: Velit quia commodi dolorem.
      area: In harum dolores consequatur et.
      county: Ipsum optio magnam eos.
      email: Et non similique.
      facebook: Eos earum vitae magnam sunt.
      firstName: Quod sunt quibusdam suscipit eos sequi dolores.
      id: Dolor mollitia.
      image: Recusandae aut.
      party: Recusandae qui mollitia blanditiis corrupti.
      phone: Omnis aspernatur dignissimos eligendi.
      secondName: Eligendi aut corporis.
      twitter: Iste cumque cum ea quod.
      web: Aliquam qui.
    - address: Velit quia commodi dolorem.
      area: In harum dolores consequatur et.
      county: Ipsum optio magnam eos.
      email: Et non similique.
      facebook: Eos earum vitae magnam sunt.
      firstName: Quod sunt quibusdam suscipit eos sequi dolores.
      id: Dolor mollitia.
      image: Recusandae aut.
      party: Recusandae qui mollitia blanditiis corrupti.
      phone: Omnis aspernatur dignissimos eligendi.
      secondName: Eligendi aut corporis.
      twitter: Iste cumque cum ea quod.
      web: Aliquam qui.
    - address: Velit quia commodi dolorem.
      area: In harum dolores consequatur et.
      county: Ipsum optio magnam eos.
      email: Et non similique.
      facebook: Eos earum vitae magnam sunt.
      firstName: Quod sunt quibusdam suscipit eos sequi dolores.
      id: Dolor mollitia.
      image: Recusandae aut.
      party: Recusandae qui mollitia blanditiis corrupti.
      phone: Omnis aspernatur dignissimos eligendi.
      secondName: Eligendi aut corporis.
      twitter: Iste cumque cum ea quod.
      web: Aliquam qui.
    items:
      $ref: '#/definitions/GoaLocalCouncillor'
    title: 'Mediatype identifier: application/vnd.goa.local.councillor+json; type=collection'
    type: array
  GoaLocalUser:
    description: A User of locals (default view)
    example:
      area: Eum natus aut sapiente.
      county: Facilis ratione odio et.
      email: Doloribus in.
      firstName: Inventore optio.
      href: Rerum debitis.
      id: Et sapiente nihil quod.
      secondName: Impedit minima voluptas ea.
      signupType: Aut sed sapiente nemo rerum eum.
      type: Nobis enim nesciunt minima.
    properties:
      area:
        description: The area of the users local council
        example: Eum natus aut sapiente.
        type: string
      county:
        description: The county the user lives in
        example: Facilis ratione odio et.
        type: string
      email:
        description: The email of the user
        example: Doloribus in.
        type: string
      firstName:
        description: Name of the user
        example: Inventore optio.
        type: string
      href:
        description: API href for making requests on the bottle
        example: Rerum debitis.
        type: string
      id:
        description: Unique bottle ID
        example: Et sapiente nihil quod.
        type: string
      secondName:
        description: Name of the user
        example: Impedit minima voluptas ea.
        type: string
      signupType:
        description: the signupType of user google local
        example: Aut sed sapiente nemo rerum eum.
        type: string
      type:
        default: local
        description: the type of user admin local councillor
        example: Nobis enim nesciunt minima.
        type: string
    required:
    - firstName
    - secondName
    - email
    title: 'Mediatype identifier: application/vnd.goa.local.user+json; view=default'
    type: object
  GoaLocalUserCollection:
    description: GoaLocalUserCollection is the media type for an array of GoaLocalUser
      (default view)
    example:
    - area: Eum natus aut sapiente.
      county: Facilis ratione odio et.
      email: Doloribus in.
      firstName: Inventore optio.
      href: Rerum debitis.
      id: Et sapiente nihil quod.
      secondName: Impedit minima voluptas ea.
      signupType: Aut sed sapiente nemo rerum eum.
      type: Nobis enim nesciunt minima.
    - area: Eum natus aut sapiente.
      county: Facilis ratione odio et.
      email: Doloribus in.
      firstName: Inventore optio.
      href: Rerum debitis.
      id: Et sapiente nihil quod.
      secondName: Impedit minima voluptas ea.
      signupType: Aut sed sapiente nemo rerum eum.
      type: Nobis enim nesciunt minima.
    - area: Eum natus aut sapiente.
      county: Facilis ratione odio et.
      email: Doloribus in.
      firstName: Inventore optio.
      href: Rerum debitis.
      id: Et sapiente nihil quod.
      secondName: Impedit minima voluptas ea.
      signupType: Aut sed sapiente nemo rerum eum.
      type: Nobis enim nesciunt minima.
    items:
      $ref: '#/definitions/GoaLocalUser'
    title: 'Mediatype identifier: application/vnd.goa.local.user+json; type=collection'
    type: array
  Location:
    example:
      Lat: 0.4236992
      Lon: 0.18768041
    properties:
      Lat:
        example: 0.4236992
        format: double
        type: number
      Lon:
        example: 0.18768041
        format: double
        type: number
    title: Location
    type: object
  Login:
    example:
      email: Qui velit natus officia reiciendis aut.
      signupType: Recusandae perferendis et optio id expedita.
      token: Aliquam exercitationem earum provident qui.
    properties:
      email:
        example: Qui velit natus officia reiciendis aut.
        type: string
      signupType:
        example: Recusandae perferendis et optio id expedita.
        type: string
      token:
        example: Aliquam exercitationem earum provident qui.
        type: string
    required:
    - email
    - token
    - signupType
    title: Login
    type: object
  UpdateUser:
    example:
      area: Voluptas consectetur.
      county: A sapiente ut iure ex aperiam et.
      email: Alias cumque error consequatur ducimus asperiores iste.
      firstName: Praesentium rerum voluptatem ea iusto explicabo.
      id: Distinctio similique eum et molestiae laudantium voluptatum.
      image: Tempora aut aut nesciunt.
      secondName: Accusantium sit.
    properties:
      area:
        default: ""
        description: The area of the users local council
        example: Voluptas consectetur.
        type: string
      county:
        default: ""
        description: The area of the users local council
        example: A sapiente ut iure ex aperiam et.
        type: string
      email:
        description: The email of the user
        example: Alias cumque error consequatur ducimus asperiores iste.
        type: string
      firstName:
        description: Name of the user
        example: Praesentium rerum voluptatem ea iusto explicabo.
        type: string
      id:
        description: Unique user ID
        example: Distinctio similique eum et molestiae laudantium voluptatum.
        type: string
      image:
        default: ""
        description: an image url for the user
        example: Tempora aut aut nesciunt.
        type: string
      secondName:
        description: Name of the user
        example: Accusantium sit.
        type: string
    required:
    - firstName
    - secondName
    - email
    - id
    - area
    title: UpdateUser
    type: object
  User:
    example:
      ID: Pariatur ut.
      area: Molestiae voluptatem quis voluptates.
      county: Eaque quia ut ut.
      email: Ad quia quo sequi minus dolores.
      firstName: Praesentium veniam soluta quia delectus dolor facere.
      image: Qui aliquid fugit.
      location:
        Lat: 0.4236992
        Lon: 0.18768041
      secondName: Nulla explicabo eum et non eveniet earum.
      signupType: Qui repudiandae dicta.
      token: Praesentium delectus rem aliquam sed.
      type: Quam fugit.
    properties:
      ID:
        default: ""
        description: Unique user ID
        example: Pariatur ut.
        type: string
      area:
        default: ""
        description: The area of the users local council
        example: Molestiae voluptatem quis voluptates.
        type: string
      county:
        default: ""
        description: The area of the users local council
        example: Eaque quia ut ut.
        type: string
      email:
        description: The email of the user
        example: Ad quia quo sequi minus dolores.
        type: string
      firstName:
        description: Name of the user
        example: Praesentium veniam soluta quia delectus dolor facere.
        type: string
      image:
        default: ""
        description: an image url for the user
        example: Qui aliquid fugit.
        type: string
      location:
        $ref: '#/definitions/Location'
      secondName:
        description: Name of the user
        example: Nulla explicabo eum et non eveniet earum.
        type: string
      signupType:
        default: ""
        description: the signupType of user google local
        example: Qui repudiandae dicta.
        type: string
      token:
        description: This can be an oauth token or a password
        example: Praesentium delectus rem aliquam sed.
        type: string
      type:
        default: local
        description: the type of user admin local councillor
        example: Quam fugit.
        type: string
    required:
    - firstName
    - secondName
    - email
    - token
    title: User
    type: object
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error'
    type: object
host: localhost:3000
info:
  description: A platform for interacting with you and local government
  title: You and local government
  version: ""
paths:
  /admin/councillor:
    post:
      description: |-
        admin api to add a councillor

        Required security scopes:
          * `admin:access`
      operationId: admin#createCouncillor
      responses:
        "201":
          description: Created
        "401":
          description: Unauthorized
      schemes:
      - http
      security:
      - jwt:
        - admin:access
      summary: createCouncillor admin
      tags:
      - admin
  /councillors/{county}:
    get:
      description: |-
        list councillors based on a users details

        Required security scopes:
          * `api:access`
      operationId: councillors#listForCountyAndArea
      parameters:
      - description: The area of the users local council
        in: query
        name: area
        required: false
        type: string
      - description: The county the user lives in
        in: path
        name: county
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GoaLocalCouncillorCollection'
        "401":
          description: Unauthorized
      schemes:
      - http
      security:
      - jwt:
        - api:access
      summary: listForCountyAndArea councillors
      tags:
      - councillors
  /swagger-ui/{filepath}:
    get:
      operationId: swagger#/swagger-ui/*filepath
      parameters:
      - description: Relative file path
        in: path
        name: filepath
        required: true
        type: string
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: Download swagger-ui/
  /swagger.json:
    get:
      operationId: swagger#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
      summary: Download swagger/swagger.json
  /user:
    get:
      description: |-
        get a list user

        Required security scopes:
          * `api:access`
      operationId: user#list
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GoaLocalUserCollection'
        "401":
          description: Unauthorized
        "404":
          description: Not Found
      schemes:
      - http
      security:
      - jwt:
        - api:access
      summary: list user
      tags:
      - user
  /user/{id}:
    delete:
      description: |-
        delete a user

        Required security scopes:
          * `api:access`
      operationId: user#delete
      parameters:
      - description: user ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "202":
          description: Accepted
        "401":
          description: Unauthorized
        "404":
          description: Not Found
      schemes:
      - http
      security:
      - jwt:
        - api:access
      summary: delete user
      tags:
      - user
    get:
      description: |-
        get a user

        Required security scopes:
          * `api:access`
      operationId: user#read
      parameters:
      - description: user ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GoaLocalUser'
        "401":
          description: Unauthorized
        "404":
          description: Not Found
      schemes:
      - http
      security:
      - jwt:
        - api:access
      summary: read user
      tags:
      - user
    post:
      description: |-
        update a user

        Required security scopes:
          * `api:access`
      operationId: user#update
      parameters:
      - description: user ID
        in: path
        name: id
        required: true
        type: string
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UpdateUser'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GoaLocalUser'
        "401":
          description: Unauthorized
        "404":
          description: Not Found
      schemes:
      - http
      security:
      - jwt:
        - api:access
      summary: update user
      tags:
      - user
  /user/login:
    post:
      description: login user
      operationId: user#login
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/Login'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GoaLocalUser'
      schemes:
      - http
      summary: login user
      tags:
      - user
  /user/signup:
    post:
      description: Signup a user
      operationId: user#signup
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/User'
      responses:
        "201":
          description: Created
        "404":
          description: Not Found
      schemes:
      - http
      summary: signup user
      tags:
      - user
produces:
- application/json
responses:
  Accepted:
    description: Accepted
  Created:
    description: Created
  NotFound:
    description: Not Found
  OK:
    description: OK
    schema:
      $ref: '#/definitions/GoaLocalUser'
  Unauthorized:
    description: Unauthorized
schemes:
- http
securityDefinitions:
  jwt:
    description: |2-


      **Security Scopes**:
        * `api:access`: API access
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
